name: "Toska slackbot-action"
description: "Post messages enriched with toska swag to slack"
inputs:
  webhook-url:
    description: "Pingviini webhook url for some channel"
    required: true
  message-type:
    description: "Kind of message you want to send."
    required: true
  header-emoji:
    description: "choose emoji to append to message header"
    required: false
    default: "kurkkumopo"

runs:
  using: "node12"
  main: "index.js"
