name: 'Toska slackbot-action'
description: 'Post messages enriched with toska swag to slack'
inputs:
  webhook-url:
    description: 'Pingviini webhook url for some channel'
    required: true
  header:
    description: 'Header for pingviini message'
    required: true
  body:
    description: 'Optional body for pingviini message, accepts markdown'
    required: false
  cat_gif:
    description: 'Optional cat gif image'
    required: false
    default: false
  cat_gif_type:
    description: 'Optional cat gif image type (fail, success or whatever). '
    required: false
    default: fail

runs:
  using: 'node12'
  main: 'index.js'
