name: "Toska slackbot-action"
description: "Post messages enriched with toska swag to slack"
inputs:
  webhook-url:
    description: "Pingviini webhook url for some channel"
    required: true
  message-type:
    description: "Kind of message you want to send."
    required: true
  softa-url:
    description: "Url for softa, will be a link in deployment mesage"
    required: false
  deployment-target:
    description: "Optionally append deployment target to deployment message"
    required: false

runs:
  using: "node12"
  main: "index.js"
